import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {RefreshCw,ShieldCheck,Users,BriefcaseBusiness,DollarSign,TrendingUp,AlertTriangle,Search,MousePointerClick,ShoppingCart} from 'lucide-react';
import {supabase} from './supabase';
import './sales-team-analytics.css';
const money=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v)||0);
const n=(v:any)=>new Intl.NumberFormat('en-US').format(Number(v)||0);
const pct=(v:any)=>`${Number(v||0).toFixed(2)}%`;
type Granularity='hour'|'day'|'week'|'month';
type Point={bucket_start:string;clicks:number;unique_clicks:number;conversions:number;orders:number;revenue:number;commission:number;campaign_earnings:number;contract_earnings:number};
export default function AdminSalesTeamIntelligence(){
 const [days,setDays]=useState(30); const [granularity,setGranularity]=useState<Granularity>('day'); const [data,setData]=useState<any>(null); const [points,setPoints]=useState<Point[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [searching,setSearching]=useState(false); const [searchResults,setSearchResults]=useState<any[]>([]);
 const load=useCallback(async()=>{setLoading(true);setError('');const end=new Date();const start=new Date(end);start.setDate(start.getDate()-days);const [summary,series]=await Promise.all([supabase.rpc('admin_sales_team_intelligence_current',{p_start:start.toISOString(),p_end:end.toISOString()}),supabase.rpc('admin_sales_team_timeseries',{p_start:start.toISOString(),p_end:end.toISOString(),p_granularity:granularity})]);if(summary.error){setError(summary.error.message);setData(null)}else setData(summary.data);if(series.error){setError(series.error.message);setPoints([])}else setPoints((series.data||[]) as Point[]);setLoading(false)},[days,granularity]);
 useEffect(()=>{load()},[load]);
 const totals=useMemo(()=>points.reduce((a,r)=>({clicks:a.clicks+Number(r.clicks||0),unique:a.unique+Number(r.unique_clicks||0),conversions:a.conversions+Number(r.conversions||0),orders:a.orders+Number(r.orders||0),revenue:a.revenue+Number(r.revenue||0)}),{clicks:0,unique:0,conversions:0,orders:0,revenue:0}),[points]);
 const search=async()=>{if(!query.trim())return;setSearching(true);setSearchResults([]);const {data,error}=await supabase.rpc('admin_universal_id_search_current',{p_public_id:query.trim()});if(!error)setSearchResults(data||[]);else setError(error.message);setSearching(false)};
 return <section className="st-analytics"><div className="st-analytics-head"><div><span>DRIGHT ADMIN</span><h2>Sales Team Intelligence</h2><p>Authorized live metrics from Supabase events and financial records. No fabricated activity.</p></div><button onClick={load} disabled={loading} title="Refresh"><RefreshCw className={loading?'spin':''} size={17}/></button></div>
 <div className="st-filters"><div className="st-pills">{[1,7,28,30,90].map(x=><button key={x} className={days===x?'active':''} onClick={()=>setDays(x)}>{x===1?'Today':`${x} days`}</button>)}</div><div className="st-selects"><select value={granularity} onChange={e=>setGranularity(e.target.value as Granularity)}><option value="hour">Hour</option><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option></select></div></div>
 {error?<div className="st-error"><ShieldCheck size={20}/><span>{error}</span><button onClick={load}>Retry</button></div>:loading?<div className="st-empty">Loading authorized Sales Team intelligence…</div>:<>
 <div className="st-kpis"><Kpi icon={<Users/>} label="Total Marketers" value={n(data?.marketers_total)}/><Kpi icon={<ShieldCheck/>} label="Approved Marketers" value={n(data?.approved_marketers)}/><Kpi icon={<Users/>} label="Pending Marketers" value={n(data?.pending_marketers)}/><Kpi icon={<BriefcaseBusiness/>} label="Advertisers" value={n(data?.advertisers)}/><Kpi icon={<BriefcaseBusiness/>} label="Active Contracts" value={n(data?.active_contracts)}/><Kpi icon={<BriefcaseBusiness/>} label="Expired Contracts" value={n(data?.expired_contracts)}/><Kpi icon={<TrendingUp/>} label="Campaigns" value={n(data?.total_campaigns)}/><Kpi icon={<TrendingUp/>} label="Sales Team Sales" value={n(data?.sales_team_generated_sales)}/><Kpi icon={<DollarSign/>} label="Generated Revenue" value={money(data?.sales_team_generated_revenue)}/><Kpi icon={<DollarSign/>} label="Platform Fees" value={money(data?.platform_fees)}/><Kpi icon={<DollarSign/>} label="Team Lead Fees" value={money(data?.team_lead_fees)}/><Kpi icon={<DollarSign/>} label="Member Earnings" value={money(data?.member_earnings)}/><Kpi icon={<DollarSign/>} label="Advertiser Earnings" value={money(data?.advertiser_earnings)}/><Kpi icon={<TrendingUp/>} label="Average Conversion" value={pct(data?.average_conversion_rate)}/><Kpi icon={<AlertTriangle/>} label="Fraud Review Volume" value={n(data?.fraud_review_volume)}/></div>
 <div className="st-kpis"><Kpi icon={<MousePointerClick/>} label="Event Clicks" value={n(totals.clicks)}/><Kpi icon={<Users/>} label="Unique Clicks" value={n(totals.unique)}/><Kpi icon={<TrendingUp/>} label="Confirmed Conversions" value={n(totals.conversions)}/><Kpi icon={<ShoppingCart/>} label="Confirmed Orders" value={n(totals.orders)}/><Kpi icon={<DollarSign/>} label="Event Revenue" value={money(totals.revenue)}/></div>
 <div className="st-grid"><MetricChart title="Sales over time" points={points} field="orders" format={n}/><MetricChart title="Revenue over time" points={points} field="revenue" format={money}/></div>
 <div className="st-grid"><MetricChart title="Clicks over time" points={points} field="clicks" format={n}/><MetricChart title="Conversions over time" points={points} field="conversions" format={n}/></div>
 <div className="st-card"><div className="st-card-head"><div><h3>Universal ID search</h3><p>Search operational IDs through the privileged server-side resolver.</p></div><Search size={18}/></div><div className="st-selects"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="User, Product, Job, Course, Task, Service, Campaign, Contract, Order, Transaction…"/><button onClick={search} disabled={searching||!query.trim()}>{searching?'Searching…':'Search'}</button></div>{searchResults.length>0?<div className="st-table-scroll"><table className="st-table"><thead><tr><th>Type</th><th>Public ID</th><th>Entity ID</th><th>Owner</th><th>Metadata</th></tr></thead><tbody>{searchResults.map((r,i)=><tr key={`${r.entity_type}-${r.entity_id}-${i}`}><td>{r.entity_type}</td><td>{r.public_id}</td><td>{r.entity_id}</td><td>{r.owner_user_id||'—'}</td><td><code>{JSON.stringify(r.metadata||{})}</code></td></tr>)}</tbody></table></div>:query&&!searching?<div className="st-empty">No authorized record found.</div>:null}</div>
 <div className="st-card"><div className="st-card-head"><div><h3>Available event funnel</h3><p>Only stages represented by authoritative Sales Team event tables are shown; unavailable stages are never fabricated.</p></div></div><div className="st-kpis"><Kpi icon={<MousePointerClick/>} label="Click" value={n(totals.clicks)}/><Kpi icon={<TrendingUp/>} label="Conversion" value={n(totals.conversions)}/><Kpi icon={<ShoppingCart/>} label="Order" value={n(totals.orders)}/></div></div>
 </>}</section>
}
function MetricChart({title,points,field,format}:{title:string;points:Point[];field:keyof Point;format:(v:any)=>string}){const values=points.map(p=>Number(p[field])||0);const max=Math.max(1,...values);return <div className="st-card"><div className="st-card-head"><div><h3>{title}</h3><p>Authoritative event data.</p></div><TrendingUp size={18}/></div><div className="st-chart">{points.map((p,i)=>{const v=Number(p[field])||0;return <div className="st-bar" key={p.bucket_start+i}><span style={{height:`${Math.max(3,v/max*100)}%`}} title={format(v)}/><small>{new Date(p.bucket_start).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div>})}</div></div>}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="st-kpi"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div>}
