import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Menu, Bell, Globe2, ChevronDown, ArrowRight, Sparkles, ShoppingBag, BriefcaseBusiness, GraduationCap, Megaphone, CheckCircle2, Heart, Share2, MessageCircle, ShieldCheck, Copy, ArrowLeft, SlidersHorizontal, X, Palette, UserRound, LogIn, UserPlus, LayoutDashboard, Wallet, Users, Settings, HelpCircle, LogOut} from 'lucide-react';
import './styles.css';

type ThemeKey='dark'|'light'|'system'|'custom';
type CustomTheme='sky'|'graphite'|'violet';
type Product={id:string;title:string;category:string;price:string;seller:string;description:string;status:string;featured?:boolean;accent:string};

const themes:Record<ThemeKey,{label:string;description:string;className:string}>={
 dark:{label:'DRIGHT Dark',description:'Premium dark DRIGHT experience',className:'theme-dright-dark'},
 light:{label:'DRIGHT Light',description:'Clean white with a soft sky-blue atmosphere',className:'theme-dright-light'},
 system:{label:'DRIGHT System',description:'Follows your device light/dark preference',className:'theme-dright-system'},
 custom:{label:'Custom Themes',description:'Cocoa, Forest and Aubergine professional palettes',className:'theme-custom'}
};
const customThemes:Record<CustomTheme,{label:string;description:string;className:string}>={
 sky:{label:'Cocoa',description:'Deep espresso brown with warm bronze accents',className:'custom-sky'},
 graphite:{label:'Forest',description:'Deep evergreen with refined green accents',className:'custom-graphite'},
 violet:{label:'Aubergine',description:'Deep plum with elegant purple accents',className:'custom-violet'}
};

function DrightLogoIcon({compact=false}:{compact?:boolean}){return <div className={`dright-logo ${compact?'dright-logo-compact':''}`} aria-label="DRIGHT"><div className="dright-logo-tile"><svg viewBox="0 0 100 100" className="dright-logo-svg" fill="none" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="brushedMetal" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#ffffff"/><stop offset="25%" stopColor="#e2e8f0"/><stop offset="50%" stopColor="#94a3b8"/><stop offset="75%" stopColor="#cbd5e1"/><stop offset="100%" stopColor="#64748b"/></linearGradient><linearGradient id="bevelEdge" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stopColor="#ffffff" stopOpacity="0.9"/><stop offset="100%" stopColor="#0f172a" stopOpacity="0.9"/></linearGradient></defs><path d="M26 15 H52 C72 15 85 28 85 50 C85 72 72 85 52 85 H26 V15 Z M42 32 V68 H51 C62 68 68 60 68 50 C68 40 62 32 51 32 H42 Z" fill="url(#bevelEdge)" transform="translate(0,2)"/><path d="M26 15 H52 C72 15 85 28 85 50 C85 72 72 85 52 85 H26 V15 Z M41 31 V69 H51 C63 69 69 61 69 50 C69 39 63 31 51 31 H41 Z" fill="url(#brushedMetal)" stroke="#475569" strokeWidth="0.5"/></svg></div><span>DRIGHT</span></div>}

const categories=[{label:'Products',icon:ShoppingBag,desc:'Digital and physical offers'},{label:'Services',icon:BriefcaseBusiness,desc:'Experts and professional work'},{label:'Courses',icon:GraduationCap,desc:'Learning and education'},{label:'Campaigns',icon:Megaphone,desc:'Promotions and creator campaigns'},{label:'Jobs',icon:BriefcaseBusiness,desc:'Opportunities and tasks'},{label:'Stores',icon:ShoppingBag,desc:'Discover independent sellers'}];
const products:Product[]=[
{id:'DR-TEST-001',title:'AI Content Strategy Kit',category:'Digital Product',price:'$29',seller:'Dright Studio',description:'A practical toolkit for planning high-converting AI-assisted content campaigns.',status:'Published',featured:true,accent:'linear-gradient(135deg,#2563eb,#7c3aed)'},
{id:'DR-TEST-002',title:'Brand Identity Sprint',category:'Services',price:'$180',seller:'Northstar Creative',description:'A focused brand strategy and identity sprint for growing digital businesses.',status:'Published',accent:'linear-gradient(135deg,#0f766e,#14b8a6)'},
{id:'DR-TEST-003',title:'Prompt Engineering Masterclass',category:'Courses',price:'$49',seller:'AI Academy',description:'Learn practical prompt design, evaluation and workflow building for modern AI tools.',status:'Published',featured:true,accent:'linear-gradient(135deg,#ea580c,#f59e0b)'},
{id:'DR-TEST-004',title:'Social Launch Campaign',category:'Campaigns',price:'$75',seller:'Growth Lab',description:'A ready-to-run campaign package for creators launching a new digital offer.',status:'Published',accent:'linear-gradient(135deg,#be185d,#8b5cf6)'},
{id:'DR-TEST-005',title:'Frontend Product Designer',category:'Jobs',price:'$1,200',seller:'DRIGHT Marketplace',description:'Example marketplace job listing used only for frontend testing.',status:'Published',accent:'linear-gradient(135deg,#334155,#64748b)'},
{id:'DR-TEST-006',title:'Creator Growth Dashboard',category:'Digital Product',price:'$39',seller:'Metric House',description:'A sample analytics template for creators tracking audience and revenue growth.',status:'Published',accent:'linear-gradient(135deg,#0369a1,#06b6d4)'}];

function App(){
 const [theme,setTheme]=useState<ThemeKey>(()=>(localStorage.getItem('dright-theme') as ThemeKey)||'dark');
 const [customTheme,setCustomTheme]=useState<CustomTheme>(()=>(localStorage.getItem('dright-custom-theme') as CustomTheme)||'sky');
 const [signedIn,setSignedIn]=useState(false);
 const [page,setPage]=useState<'welcome'|'market'|'product'>('welcome'); const [selected,setSelected]=useState<Product|null>(null); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [sort,setSort]=useState('Recommended'); const [themeOpen,setThemeOpen]=useState(false); const [sidebarOpen,setSidebarOpen]=useState(false);
 useEffect(()=>{localStorage.setItem('dright-theme',theme);localStorage.setItem('dright-custom-theme',customTheme)},[theme,customTheme]);
 const filtered=useMemo(()=>{let list=products.filter(p=>(category==='All'||p.category===category)&&(`${p.title} ${p.category} ${p.seller}`.toLowerCase().includes(query.toLowerCase())));if(sort==='Price: Low to High')list=[...list].sort((a,b)=>Number(a.price.replace(/[^0-9.]/g,''))-Number(b.price.replace(/[^0-9.]/g,'')));if(sort==='Featured')list=[...list].sort((a,b)=>Number(b.featured)-Number(a.featured));return list},[query,category,sort]);
 const openProduct=(p:Product)=>{setSelected(p);setPage('product');window.scrollTo({top:0,behavior:'smooth'})};
 const shellTheme=theme==='custom'?customThemes[customTheme].className:themes[theme].className;
 return <div className={`app ${shellTheme}`}>
   <Header signedIn={signedIn} query={query} setQuery={setQuery} onMarket={()=>setPage('market')} onWelcome={()=>setPage('welcome')} onTheme={()=>setThemeOpen(v=>!v)} onSignIn={()=>setSignedIn(true)} onSignUp={()=>setSignedIn(true)} onMenu={()=>setSidebarOpen(v=>!v)} />
   {signedIn&&<Sidebar open={sidebarOpen} onClose={()=>setSidebarOpen(false)} onWelcome={()=>setPage('welcome')} onMarket={()=>setPage('market')} />}
   {themeOpen&&<ThemePicker theme={theme} customTheme={customTheme} setTheme={setTheme} setCustomTheme={setCustomTheme} close={()=>setThemeOpen(false)}/>} 
   {page==='welcome'&&<Welcome signedIn={signedIn} onMarket={()=>setPage('market')} query={query} setQuery={setQuery} onProduct={openProduct}/>} 
   {page==='market'&&<Market query={query} setQuery={setQuery} category={category} setCategory={setCategory} sort={sort} setSort={setSort} products={filtered} onProduct={openProduct} back={()=>setPage('welcome')}/>} 
   {page==='product'&&selected&&<ProductDetails product={selected} back={()=>setPage('market')} onProduct={openProduct}/>} <Footer/>
 </div>;
}

function Header({signedIn,query,setQuery,onMarket,onWelcome,onTheme,onSignIn,onSignUp,onMenu}:{signedIn:boolean;query:string;setQuery:(v:string)=>void;onMarket:()=>void;onWelcome:()=>void;onTheme:()=>void;onSignIn:()=>void;onSignUp:()=>void;onMenu:()=>void}){return <header className="topbar"><div className="topbar-brand" onClick={onWelcome}><DrightLogoIcon compact/></div><nav className="desktop-nav"><button onClick={onMarket}>Marketplace</button><button>AI tools</button><button>For business</button></nav><div className="header-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, services, courses, jobs and more..."/><kbd>⌘ K</kbd></div><div className="header-actions"><button className="icon-btn" aria-label="Language"><Globe2 size={18}/><span className="header-label">EN</span></button><button className="icon-btn" aria-label="Notifications"><Bell size={18}/></button><button className="theme-trigger" onClick={onTheme}><Palette size={16}/><span>Theme</span><ChevronDown size={14}/></button>{signedIn?<button className="profile-avatar" aria-label="User profile"><UserRound size={22}/></button>:<><button className="guest-action" onClick={onMarket}>Browse</button><button className="guest-action" onClick={onSignIn}><LogIn size={15}/> Sign in</button><button className="guest-primary" onClick={onSignUp}><UserPlus size={15}/> Sign up</button></>} {signedIn&&<button className="menu-btn" onClick={onMenu}><Menu size={20}/></button>}</div></header>}

function Sidebar({open,onClose,onWelcome,onMarket}:{open:boolean;onClose:()=>void;onWelcome:()=>void;onMarket:()=>void}){return <aside className={`left-sidebar ${open?'open':''}`}><div className="sidebar-logo"><DrightLogoIcon/></div><div className="sidebar-nav"><button onClick={onWelcome}><LayoutDashboard size={18}/> Dashboard</button><button onClick={onMarket}><ShoppingBag size={18}/> Marketplace</button><button><Users size={18}/> Referral</button><button><Wallet size={18}/> Wallet</button><button><Heart size={18}/> Favorites</button><button><MessageCircle size={18}/> Messages</button><button><Bell size={18}/> Notifications</button><button><Settings size={18}/> Settings</button><button><HelpCircle size={18}/> Help & Support</button></div><div className="sidebar-bottom"><button><LogOut size={18}/> Logout</button></div><button className="sidebar-close" onClick={onClose}><X size={18}/></button></aside>}

function ThemePicker({theme,customTheme,setTheme,setCustomTheme,close}:{theme:ThemeKey;customTheme:CustomTheme;setTheme:(v:ThemeKey)=>void;setCustomTheme:(v:CustomTheme)=>void;close:()=>void}){return <div className="theme-popover"><div className="theme-head"><div><strong>DRIGHT themes</strong><span>Choose your platform appearance</span></div><button onClick={close}><X size={18}/></button></div><div className="theme-grid">{Object.entries(themes).map(([key,t])=><button key={key} className={`theme-option ${theme===key?'selected':''}`} onClick={()=>{setTheme(key as ThemeKey);close()}}><span className={`theme-swatch ${t.className}`}><i/><i/><i/></span><span><strong>{t.label}</strong><small>{t.description}</small></span>{theme===key&&<CheckCircle2 size={16}/>}</button>)}</div>{theme==='custom'&&<div className="custom-theme-list">{Object.entries(customThemes).map(([key,t])=><button key={key} className={customTheme===key?'custom-selected':''} onClick={()=>setCustomTheme(key as CustomTheme)}><span className={`custom-dot ${t.className}`}/><span><strong>{t.label}</strong><small>{t.description}</small></span></button>)}</div>}</div>}

function Welcome({signedIn,onMarket,query,setQuery,onProduct}:{signedIn:boolean;onMarket:()=>void;query:string;setQuery:(v:string)=>void;onProduct:(p:Product)=>void}){return <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="pulse"/>AI-powered marketplace</span><h1>Discover something that <em>moves you forward.</em></h1><p>Explore products, services, courses, jobs and opportunities across the DRIGHT ecosystem — built for people who create, sell, learn and grow.</p><div className="hero-search"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, keyword or listing ID..."/><button onClick={onMarket}>Explore <ArrowRight size={17}/></button></div><div className="hero-actions"><button className="primary" onClick={onMarket}>Explore marketplace</button><button className="secondary">{signedIn?'Open dashboard':'Start selling'} <ArrowRight size={16}/></button></div></div><div className="hero-panel"><div className="ai-card"><Sparkles size={20}/><span>DRIGHT AI</span><strong>Find the right opportunity faster.</strong><p>Search across products, services, learning and work from one intelligent marketplace.</p></div><div className="mini-stat"><span>Marketplace</span><strong>Always discovering</strong><div className="avatar-stack"><i/><i/><i/><b>+</b></div></div></div></section><section className="section"><div className="section-heading"><div><span className="section-kicker">Explore</span><h2>Everything in one marketplace</h2></div><button className="text-btn" onClick={onMarket}>See all <ArrowRight size={15}/></button></div><div className="category-grid">{categories.map(c=><button className="category-card" key={c.label} onClick={onMarket}><span className="category-icon"><c.icon size={22}/></span><strong>{c.label}</strong><small>{c.desc}</small></button>)}</div></section><section className="section"><div className="section-heading"><div><span className="section-kicker">For you</span><h2>Featured opportunities</h2></div><button className="text-btn" onClick={onMarket}>Browse marketplace <ArrowRight size={15}/></button></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p} onClick={()=>onProduct(p)}/>)}</div></section></main>}

function Market({query,setQuery,category,setCategory,sort,setSort,products,onProduct,back}:{query:string;setQuery:(v:string)=>void;category:string;setCategory:(v:string)=>void;sort:string;setSort:(v:string)=>void;products:Product[];onProduct:(p:Product)=>void;back:()=>void}){const cats=['All','Products','Services','Courses','Jobs','Tasks'];return <main className="market-page"><button className="back-link" onClick={back}><ArrowLeft size={16}/> Welcome</button><section className="market-hero"><span className="section-kicker">DRIGHT Marketplace</span><h1>Find products, services and opportunities.</h1><p>Discover listings from the growing DRIGHT ecosystem.</p><div className="market-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, keyword or listing ID..."/></div></section><div className="filter-row"><div className="category-pills">{cats.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="sort"><SlidersHorizontal size={16}/><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Featured</option><option>Price: Low to High</option></select></label></div><div className="market-meta"><strong>{products.length} listings</strong><span>Example/test content for frontend development</span></div><div className="product-grid market-grid">{products.map(p=><ProductCard key={p.id} product={p} onClick={()=>onProduct(p)}/>)}</div></main>}

function ProductCard({product,onClick}:{product:Product;onClick:()=>void}){return <button className="product-card" onClick={onClick}><div className="product-image" style={{background:product.accent}}><span>{product.category}</span></div><div className="product-body"><div className="product-top"><small>{product.category}</small><span><Heart size={15}/></span></div><strong>{product.title}</strong><p>{product.description}</p><div className="product-foot"><b>{product.price}</b><span>{product.seller}</span></div></div></button>}

function ProductDetails({product,back,onProduct}:{product:Product;back:()=>void;onProduct:(p:Product)=>void}){return <main className="product-page"><button className="back-link" onClick={back}><ArrowLeft size={16}/> Marketplace</button><div className="product-detail"><div className="product-detail-image" style={{background:product.accent}}><span>{product.category}</span></div><div><span className="section-kicker">{product.category}</span><h1>{product.title}</h1><p>{product.description}</p><strong>{product.price}</strong><div className="detail-actions"><button className="primary">Buy / enquire</button><button className="secondary"><Share2 size={16}/> Share</button></div></div></div></main>}

function Footer(){return <footer className="site-footer"><span>© 2026 DRIGHT</span><span>AI-powered marketplace for products, services, learning and opportunities.</span></footer>}

createRoot(document.getElementById('root')!).render(<App/>);
