import React,{useCallback,useEffect,useState} from 'react';
import {Activity,AlertTriangle,BarChart3,CheckCircle2,ChevronRight,Clock3,DollarSign,Filter,Layers,MousePointerClick,Pause,Play,RefreshCw,Search,ShieldCheck,Users,WalletCards,XCircle} from 'lucide-react';
import {supabase} from './supabase';
import './promotion-control-center.css';

type Tab='overview'|'campaigns'|'analytics'|'affiliates'|'fraud'|'configuration'|'audit';
type Range=1|7|30|90;
type Campaign={promotion_id:string;campaign_id:string;owner_id:string;owner_name:string;asset_id:string|null;asset_public_id:string|null;asset_name:string;asset_type:string;status:string;currency:string;spend:number;impressions:number;reach:number;clicks:number;ctr:number;conversions:number;conversion_rate:number;revenue:number;roas:number;starts_at:string|null;ends_at:string|null;created_at:string};
type Affiliate={affiliate_id:string;user_id:string;affiliate_name:string;clicks:number;unique_clicks:number;orders:number;revenue:number;commission:number;reversed_commissions:number;refund_related_orders:number};
type State={overview:Record<string,any>;campaigns:Campaign[];affiliates:Affiliate[];fraud:any[];config:Record<string,any>;generated_at:string};
type Point={bucket_start:string;impressions:number;reach:number;views:number;clicks:number;conversions:number;spend:number;revenue:number};
const n=(v:any)=>new Intl.NumberFormat('en-US').format(Number(v)||0);const m=(v:any,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v)||0);const d=(v:any)=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';

export default function PromotionControlCenter(){const [tab,setTab]=useState<Tab>('overview');const [range,setRange]=useState<Range>(30);const [state,setState]=useState<State|null>(null);const [series,setSeries]=useState<Point[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [q,setQ]=useState('');const [results,setResults]=useState<any[]>([]);const [selected,setSelected]=useState<Campaign|null>(null);const [affiliate,setAffiliate]=useState<Affiliate|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');const end=new Date(),start=new Date(end);start.setDate(start.getDate()-range);const [a,b]=await Promise.all([supabase.rpc('admin_promotion_control_center',{p_start:start.toISOString(),p_end:end.toISOString()}),supabase.rpc('admin_promotion_timeseries',{p_start:start.toISOString(),p_end:end.toISOString(),p_granularity:range===1?'hour':'day'})]);if(a.error){setError(a.error.message);setState(null)}else setState(a.data as State);if(!b.error)setSeries((b.data||[]) as Point[]);setLoading(false)},[range]);useEffect(()=>{load()},[load]);
 const searchId=async()=>{if(!q.trim())return;const {data,error:e}=await supabase.rpc('admin_universal_id_search_current',{p_public_id:q.trim()});if(e)setError(e.message);else setResults(data||[])};
 return <section className="pcc"><header className="pcc-header"><div><div className="pcc-eyebrow">DRIGHT SUPER ADMIN</div><h1>Promotion Control Center</h1><p>Universal promotion operations, analytics, attribution and risk.</p></div><div className="pcc-head-actions"><select value={range} onChange={e=>setRange(Number(e.target.value) as Range)}><option value={1}>24 hours</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select><button className="pcc-refresh" onClick={load} disabled={loading}><RefreshCw size={17}/>Refresh</button></div></header><div className="pcc-id-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchId()} placeholder="Search DRIGHT universal ID"/><button onClick={searchId}>Search</button></div>{results.length>0&&<div className="pcc-search-results">{results.map((r:any,i)=><button key={i} onClick={()=>setResults([])}><span><strong>{r.public_id}</strong><small>{r.entity_type}</small></span><ChevronRight size={16}/></button>)}</div>}<div className="pcc-tabs">{(['overview','campaigns','analytics','affiliates','fraud','configuration','audit'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{label(x)}</button>)}</div>{error&&<div className="pcc-error"><AlertTriangle size={18}/><span>{error}</span><button onClick={load}>Retry</button></div>}{loading?<div className="pcc-loading">Loading authorized promotion intelligence…</div>:state&&<>{tab==='overview'&&<Overview o={state.overview} c={state.campaigns} a={state.affiliates} pick={setSelected} pickA={setAffiliate}/>} {tab==='campaigns'&&<Campaigns rows={state.campaigns} pick={setSelected}/>} {tab==='analytics'&&<Analytics o={state.overview} s={series}/>} {tab==='affiliates'&&<AffiliateTable rows={state.affiliates} pick={setAffiliate}/>} {tab==='fraud'&&<Fraud rows={state.fraud}/>} {tab==='configuration'&&<Configuration config={state.config}/>} {tab==='audit'&&<Audit/>}</>}{selected&&<CampaignDrawer campaign={selected} close={()=>setSelected(null)} refresh={load}/>} {affiliate&&<AffiliateDrawer a={affiliate} close={()=>setAffiliate(null)} range={range}/>}</section>}
function label(x:Tab){return x==='affiliates'?'Affiliate Intelligence':x==='fraud'?'Fraud & Risk':x==='configuration'?'Configuration':x==='audit'?'Audit History':x[0].toUpperCase()+x.slice(1)}
function Overview({o,c,a,pick,pickA}:{o:Record<string,any>;c:Campaign[];a:Affiliate[];pick:(x:Campaign)=>void;pickA:(x:Affiliate)=>void}){const cards:[string,string,React.ElementType][]=[['Campaigns',n(o.total_campaigns),Layers],['Active',n(o.active_campaigns),Activity],['Spend',m(o.spend),DollarSign],['Impressions',n(o.impressions),BarChart3],['Reach',n(o.reach),Users],['Clicks',n(o.clicks),MousePointerClick],['Conversions',n(o.conversions),ShieldCheck],['Revenue',m(o.revenue),WalletCards],['ROAS',o.spend?`${(Number(o.revenue)/Number(o.spend)).toFixed(2)}x`:'No data yet',Activity],['Refunds',m(o.refunds),AlertTriangle],['Fraud reviews',n(o.fraud_reviews),AlertTriangle]];return <><div className="pcc-kpis">{cards.map(([x,v,I])=><div className="pcc-kpi" key={x}><span><I size={18}/></span><small>{x}</small><strong>{v}</strong></div>)}</div><div className="pcc-two"><div className="pcc-card"><Title t="Recent campaigns" i={<Layers size={18}/>}/><CampaignTable rows={c.slice(0,8)} pick={pick}/></div><div className="pcc-card"><Title t="Affiliate intelligence" i={<Users size={18}/>}/><AffiliateTable rows={a.slice(0,8)} pick={pickA}/></div></div></>}
function Campaigns({rows,pick}:{rows:Campaign[];pick:(x:Campaign)=>void}){const [q,setQ]=useState('');const r=rows.filter(x=>`${x.campaign_id} ${x.owner_name} ${x.asset_name} ${x.asset_public_id||''} ${x.status}`.toLowerCase().includes(q.toLowerCase()));return <div className="pcc-card"><div className="pcc-toolbar"><Title t="Campaign management" i={<Layers size={18}/>}/><div className="pcc-inline-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter campaigns"/></div></div><CampaignTable rows={r} pick={pick}/></div>}
function CampaignTable({rows,pick}:{rows:Campaign[];pick:(x:Campaign)=>void}){if(!rows.length)return <Empty text="No campaign records for this period."/>;return <div className="pcc-scroll"><table className="pcc-table"><thead><tr><th>Campaign</th><th>Owner</th><th>Asset</th><th>Status</th><th>Spend</th><th>Clicks</th><th>Conv.</th><th>Revenue</th></tr></thead><tbody>{rows.map(x=><tr key={x.promotion_id} onClick={()=>pick(x)}><td><strong>{x.campaign_id}</strong><small>{d(x.created_at)}</small></td><td>{x.owner_name}</td><td>{x.asset_public_id||'—'}<small>{x.asset_name}</small></td><td><span className="status-badge">{x.status}</span></td><td>{m(x.spend,x.currency)}</td><td>{n(x.clicks)}</td><td>{n(x.conversions)}</td><td>{m(x.revenue,x.currency)}</td></tr>)}</tbody></table></div>}
function Analytics({o,s}:{o:Record<string,any>;s:Point[]}){return <div className="pcc-card"><Title t="Recorded promotion analytics" i={<BarChart3 size={18}/>}/>{s.length?<div className="pcc-timeseries">{s.map((x,i)=><div className="pcc-time-point" key={`${x.bucket_start}-${i}`}><div className="pcc-time-bars"><i style={{height:`${pct(x.impressions,s.map(z=>z.impressions))}%`}}/><b style={{height:`${pct(x.clicks,s.map(z=>z.clicks))}%`}}/></div><small>{new Date(x.bucket_start).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div>)}</div>:<Empty text="No performance data yet."/>}<div className="pcc-chart-grid"><Chart label="Impressions" v={o.impressions}/><Chart label="Reach" v={o.reach}/><Chart label="Clicks" v={o.clicks}/><Chart label="Conversions" v={o.conversions}/><Chart label="Revenue" v={o.revenue} cash/></div><p className="pcc-note">Time series comes from the existing campaign_statistics table. Financial revenue remains authoritative to DRIGHT financial records.</p></div>}
function pct(v:number,a:number[]){const max=Math.max(1,...a.map(Number));return Math.max(4,Math.min(100,(Number(v)||0)/max*100))}
function AffiliateTable({rows,pick}:{rows:Affiliate[];pick:(x:Affiliate)=>void}){if(!rows.length)return <Empty text="No affiliate records for this period."/>;return <div className="pcc-scroll"><table className="pcc-table"><thead><tr><th>Affiliate</th><th>Clicks</th><th>Unique</th><th>Orders</th><th>Revenue</th><th>Commission</th><th>Reversed</th></tr></thead><tbody>{rows.map(x=><tr key={x.affiliate_id} onClick={()=>pick(x)}><td><strong>{x.affiliate_id}</strong><small>{x.affiliate_name}</small></td><td>{n(x.clicks)}</td><td>{n(x.unique_clicks)}</td><td>{n(x.orders)}</td><td>{m(x.revenue)}</td><td>{m(x.commission)}</td><td>{n(x.reversed_commissions)}</td></tr>)}</tbody></table></div>}
function Fraud({rows}:{rows:any[]}){return <div className="pcc-card"><Title t="Fraud & Risk" i={<AlertTriangle size={18}/>}/><p className="pcc-note">Risk signals are evidence for review, not automatic proof of fraud.</p>{rows.length?<div className="pcc-risk-list">{rows.map((x,i)=><div key={i}><span className="risk-badge">{x.status}</span><strong>{x.public_id}</strong><small>{x.signal_type} · {d(x.detected_at)} · risk {x.risk_score??0}</small></div>)}</div>:<Empty text="No fraud/risk signals for this period."/>}</div>}
function Configuration({config}:{config:Record<string,any>}){const rows=Object.entries(config);return <div className="pcc-card"><Title t="Promotion configuration" i={<Filter size={18}/>}/>{rows.length?<div className="pcc-config-list">{rows.map(([k,v])=><div key={k}><strong>{k}</strong><code>{JSON.stringify(v,null,2)}</code></div>)}</div>:<Empty text="No promotion-specific admin settings are stored here."/>}<p className="pcc-note">Existing promotion pricing/package RPCs remain the authoritative mutation path and are audited server-side.</p></div>}
function Audit(){return <div className="pcc-card"><Title t="Audit History" i={<ShieldCheck size={18}/>}/><p className="pcc-note">Promotion administrative mutations use the existing admin_audit_logs architecture. No parallel audit stream is created.</p><Empty text="Open the existing DRIGHT audit workspace for the authoritative audit history."/></div>}
function CampaignDrawer({campaign,close,refresh}:{campaign:Campaign;close:()=>void;refresh:()=>void}){const [busy,setBusy]=useState(false);const act=async(status:string)=>{if(!campaign.promotion_id)return;setBusy(true);const {error}=await supabase.rpc('admin_update_promotion_status',{p_promotion_id:campaign.promotion_id,p_status:status,p_reason:'Promotion Control Center action'});if(error)alert(error.message);else{await refresh();close()}setBusy(false)};return <Drawer title="Campaign intelligence" close={close}><div className="pcc-drawer-id">{campaign.campaign_id}</div><div className="pcc-detail-grid"><Mini l="Owner" v={campaign.owner_name}/><Mini l="Asset" v={campaign.asset_public_id||'—'}/><Mini l="Status" v={campaign.status}/><Mini l="Spend" v={m(campaign.spend,campaign.currency)}/><Mini l="Impressions" v={n(campaign.impressions)}/><Mini l="Reach" v={n(campaign.reach)}/><Mini l="Clicks" v={n(campaign.clicks)}/><Mini l="CTR" v={`${Number(campaign.ctr||0).toFixed(2)}%`}/><Mini l="Conversions" v={n(campaign.conversions)}/><Mini l="Revenue" v={m(campaign.revenue,campaign.currency)}/><Mini l="ROAS" v={campaign.spend?`${Number(campaign.roas||0).toFixed(2)}x`:'No data yet'}/><Mini l="Ends" v={d(campaign.ends_at)}/></div><div className="pcc-action-row"><button disabled={busy} onClick={()=>act('approved')}><CheckCircle2 size={15}/>Approve</button><button disabled={busy} onClick={()=>act('active')}><Play size={15}/>Resume</button><button disabled={busy} onClick={()=>act('paused')}><Pause size={15}/>Pause</button><button disabled={busy} onClick={()=>act('rejected')}><XCircle size={15}/>Reject</button><button disabled={busy} onClick={()=>act('cancelled')}><Clock3 size={15}/>Cancel</button></div></Drawer>}
function AffiliateDrawer({a,close,range}:{a:Affiliate;close:()=>void;range:number}){const [series,setSeries]=useState<any[]>([]);useEffect(()=>{const e=new Date(),s=new Date(e);s.setDate(s.getDate()-range);supabase.rpc('affiliate_analytics',{p_affiliate_user_id:a.user_id,p_from:s.toISOString(),p_to:e.toISOString()}).then(({data})=>setSeries(data||[]))},[a.user_id,range]);return <Drawer title="Affiliate intelligence" close={close}><div className="pcc-drawer-id">{a.affiliate_id}</div><div className="pcc-detail-grid"><Mini l="Affiliate" v={a.affiliate_name}/><Mini l="Clicks" v={n(a.clicks)}/><Mini l="Unique clicks" v={n(a.unique_clicks)}/><Mini l="Orders" v={n(a.orders)}/><Mini l="Revenue" v={m(a.revenue)}/><Mini l="Commission" v={m(a.commission)}/><Mini l="Refund-related" v={n(a.refund_related_orders)}/><Mini l="Reversed" v={n(a.reversed_commissions)}/></div>{!series.length&&<Empty text="No affiliate click events for this period."/>}</Drawer>}
function Drawer({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="pcc-overlay" onClick={close}><aside className="pcc-drawer" onClick={e=>e.stopPropagation()}><div className="pcc-drawer-head"><h3>{title}</h3><button onClick={close}>×</button></div>{children}</aside></div>}
function Title({t,i}:{t:string;i:React.ReactNode}){return <div className="pcc-card-title"><span>{i}</span><h3>{t}</h3></div>}function Mini({l,v}:{l:string;v:any}){return <div className="pcc-mini"><small>{l}</small><strong>{v}</strong></div>}function Chart({label,v,cash=false}:{label:string;v:any;cash?:boolean}){const value=Number(v)||0;return <div className="pcc-chart-item"><div><span>{label}</span><strong>{cash?m(value):n(value)}</strong></div><div className="pcc-chart-track"><i style={{width:`${Math.max(2,Math.min(100,value?Math.log10(Math.abs(value)+1)/12*100:2))}%`}}/></div></div>}function Empty({text}:{text:string}){return <div className="pcc-empty">{text}</div>}
