import React, {useCallback, useEffect, useMemo, useState} from 'react';
import {BarChart3, RefreshCw, ShieldCheck, TrendingUp, Users, DollarSign, MousePointerClick, ShoppingCart} from 'lucide-react';
import {supabase} from './supabase';
import './sales-team-analytics.css';

const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v)||0);
const n=(v:number)=>new Intl.NumberFormat('en-US').format(Number(v)||0);
const pct=(v:number)=>`${(Number(v)||0).toFixed(2)}%`;
type Granularity='hour'|'day'|'week'|'month';
type RangeKey='today'|'7d'|'28d'|'30d'|'90d'|'custom';
type Row={bucket_start:string;clicks:number;unique_clicks:number;conversions:number;orders:number;revenue:number;commission:number;campaign_earnings:number;contract_earnings:number};
type Member={member_user_id:string;member_id:string;public_id:string;level:number;clicks:number;conversions:number;sales:number;revenue:number;commission:number;conversion_rate:number;contract_earnings:number;status:string};
function dates(range:RangeKey,from:string,to:string){const end=to?new Date(to):new Date();let start=from?new Date(from):new Date(end);if(!from){if(range==='today')start.setHours(0,0,0,0);if(range==='7d')start.setDate(start.getDate()-7);if(range==='28d')start.setDate(start.getDate()-28);if(range==='30d')start.setDate(start.getDate()-30);if(range==='90d')start.setDate(start.getDate()-90);}return {start,end};}
export default function SalesTeamAnalytics(){
 const [range,setRange]=useState<RangeKey>('30d'); const [granularity,setGranularity]=useState<Granularity>('day'); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [rows,setRows]=useState<Row[]>([]); const [members,setMembers]=useState<Member[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const {start,end}=dates(range,from,to);const [a,m]=await Promise.all([supabase.rpc('sales_team_realtime_analytics',{p_start:start.toISOString(),p_end:end.toISOString(),p_granularity:granularity}),supabase.rpc('sales_team_member_realtime_analytics',{p_start:start.toISOString(),p_end:end.toISOString()})]);if(a.error)throw a.error;if(m.error)throw m.error;setRows((a.data||[]) as Row[]);setMembers((m.data||[]) as Member[]);}catch(e:any){setError(e?.message||'Unable to load Sales Team analytics.');setRows([]);setMembers([])}finally{setLoading(false)}},[range,granularity,from,to]);
 useEffect(()=>{load()},[load]);
 const totals=useMemo(()=>rows.reduce((a,r)=>({clicks:a.clicks+Number(r.clicks||0),unique:a.unique+Number(r.unique_clicks||0),conversions:a.conversions+Number(r.conversions||0),orders:a.orders+Number(r.orders||0),revenue:a.revenue+Number(r.revenue||0),commission:a.commission+Number(r.commission||0),campaign:a.campaign+Number(r.campaign_earnings||0),contract:a.contract+Number(r.contract_earnings||0)}),{clicks:0,unique:0,conversions:0,orders:0,revenue:0,commission:0,campaign:0,contract:0}),[rows]);
 const max=Math.max(1,...rows.map(r=>Number(r.orders||r.conversions||0)));
 return <section className="st-analytics"><div className="st-analytics-head"><div><span>DRIGHT Sales Team</span><h2>Real-time Analytics</h2><p>Live Supabase records only. No generated or estimated activity.</p></div><button onClick={load} disabled={loading} title="Refresh"><RefreshCw className={loading?'spin':''} size={17}/></button></div>
 <div className="st-filters"><div className="st-pills">{(['today','7d','28d','30d','90d','custom'] as RangeKey[]).map(x=><button key={x} className={range===x?'active':''} onClick={()=>setRange(x)}>{x==='today'?'Today':x==='7d'?'7 days':x==='28d'?'28 days':x==='30d'?'30 days':x==='90d'?'90 days':'Custom'}</button>)}</div><div className="st-selects"><select value={granularity} onChange={e=>setGranularity(e.target.value as Granularity)}><option value="hour">Hour</option><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option></select>{range==='custom'&&<><input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/><input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></>}</div></div>
 {error?<div className="st-error"><ShieldCheck size={20}/><span>{error}</span><button onClick={load}>Retry</button></div>:loading?<div className="st-empty">Loading verified analytics…</div>:<><div className="st-kpis"><Kpi icon={<MousePointerClick/>} label="Clicks" value={n(totals.clicks)}/><Kpi icon={<Users/>} label="Unique Clicks" value={n(totals.unique)}/><Kpi icon={<TrendingUp/>} label="Conversions" value={n(totals.conversions)}/><Kpi icon={<ShoppingCart/>} label="Orders" value={n(totals.orders)}/><Kpi icon={<DollarSign/>} label="Revenue" value={money(totals.revenue)}/><Kpi icon={<DollarSign/>} label="Commission" value={money(totals.commission)}/><Kpi icon={<DollarSign/>} label="Campaign Earnings" value={money(totals.campaign)}/><Kpi icon={<DollarSign/>} label="Contract Earnings" value={money(totals.contract)}/></div>
 <div className="st-grid"><div className="st-card"><div className="st-card-head"><div><h3>Sales over time</h3><p>Confirmed orders/conversions by selected period.</p></div><BarChart3 size={18}/></div><div className="st-chart">{rows.map((r,i)=>{const v=Number(r.orders||r.conversions||0);return <div className="st-bar" key={r.bucket_start+i}><span style={{height:`${Math.max(3,v/max*100)}%`}} title={`${v} sales`}/><small>{new Date(r.bucket_start).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div>})}</div></div>
 <div className="st-card"><div className="st-card-head"><div><h3>Revenue over time</h3><p>Revenue attached to confirmed Sales Team conversions.</p></div><TrendingUp size={18}/></div><div className="st-table-scroll"><table className="st-table"><thead><tr><th>Period</th><th>Revenue</th><th>Commission</th><th>Orders</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.bucket_start+i}><td>{new Date(r.bucket_start).toLocaleString()}</td><td>{money(r.revenue)}</td><td>{money(r.commission)}</td><td>{n(r.orders)}</td></tr>)}</tbody></table></div></div></div>
 <div className="st-card"><div className="st-card-head"><div><h3>Member performance</h3><p>Authoritative member-level analytics for the selected period.</p></div><Users size={18}/></div>{members.length===0?<div className="st-empty">No approved Sales Team member activity in this period.</div>:<div className="st-table-scroll"><table className="st-table"><thead><tr><th>Member</th><th>Level</th><th>Clicks</th><th>Conversions</th><th>Sales</th><th>Revenue</th><th>Commission</th><th>Conv.</th><th>Contract earnings</th><th>Status</th></tr></thead><tbody>{members.map(m=><tr key={m.member_id}><td>{m.public_id}</td><td>L{m.level}</td><td>{n(m.clicks)}</td><td>{n(m.conversions)}</td><td>{n(m.sales)}</td><td>{money(m.revenue)}</td><td>{money(m.commission)}</td><td>{pct(m.conversion_rate)}</td><td>{money(m.contract_earnings)}</td><td>{m.status}</td></tr>)}</tbody></table></div>}</div></>}
 </section>;
}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="st-kpi"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div>}
