import React,{useEffect,useMemo,useState} from 'react';
import {Archive,ArrowLeft,BarChart3,CheckCircle2,Edit3,Eye,Filter,Link2,Package,PauseCircle,Plus,RefreshCw,Search,ShieldCheck,ShoppingBag,TrendingUp,Users,X} from 'lucide-react';
import {supabase} from './supabase';
import './seller-dright-theme.css';
import './seller-product-management.css';

type Product={product_id:string;public_id:string;title:string;product_type:string;description:string|null;price:number;currency:string;status:string;affiliate_enabled:boolean;affiliate_commission_rate:number;created_at:string;updated_at:string};
type Perf={product_id:string;product_name:string;total_sales:number;organic_sales:number;affiliate_sales:number;affiliate_clicks:number;affiliate_conversion_rate:number;active_affiliates:number;affiliate_commission:number;revenue_generated:number};
const ranges=[['1','Today'],['7','7 days'],['28','28 days'],['30','30 days'],['90','90 days']] as const;
const money=(n:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(n)||0);
const num=(n:number)=>new Intl.NumberFormat('en-US').format(Number(n)||0);
const pct=(n:number)=>`${Number(n||0).toFixed(2)}%`;

export default function SellerProductManagement({back}:{back:()=>void}){
 const [products,setProducts]=useState<Product[]>([]); const [perf,setPerf]=useState<Perf[]>([]); const [promos,setPromos]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [range,setRange]=useState('30'); const [search,setSearch]=useState(''); const [type,setType]=useState('all'); const [status,setStatus]=useState('all'); const [performance,setPerformance]=useState('all');
 const [editing,setEditing]=useState<Product|null>(null); const [saving,setSaving]=useState(false); const [selected,setSelected]=useState<Product|null>(null); const [promoOpen,setPromoOpen]=useState<Product|null>(null); const [promoBudget,setPromoBudget]=useState(''); const [promoDuration,setPromoDuration]=useState('7'); const [promoGoal,setPromoGoal]=useState('views'); const [promoPackages,setPromoPackages]=useState<any[]>([]); const [promoPricing,setPromoPricing]=useState<any>(null); const [notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data:{session}}=await supabase.auth.getSession();if(!session){setError('Sign in with a Seller profile to manage products.');setLoading(false);return}const to=new Date();const from=new Date(to.getTime()-Number(range)*86400000).toISOString();const [p,pr,e,sp,pp]=await Promise.all([supabase.from('seller_products').select('*').eq('seller_user_id',session.user.id).order('updated_at',{ascending:false}),supabase.rpc('seller_product_performance',{p_from:from,p_to:to.toISOString()}),supabase.from('seller_product_events').select('product_id,event_type,occurred_at').eq('seller_user_id',session.user.id).gte('occurred_at',from),supabase.from('seller_promotions').select('promotion_id,public_id,product_id,status,impressions,clicks,conversions,revenue,spend').eq('seller_user_id',session.user.id),supabase.from('promotion_pricing').select('*').eq('status','active').order('effective_at',{ascending:false}).limit(1).maybeSingle()]);if(p.error)setError(p.error.message);setProducts((p.data||[]) as Product[]);setPerf((pr.data||[]) as Perf[]);setEvents(e.data||[]);setPromos(sp.data||[]);setPromoPricing(pp.data||null);const pk=await supabase.from('promotion_packages').select('*').eq('status','active').order('sort_order');setPromoPackages(pk.data||[]);setLoading(false)};
 useEffect(()=>{load()},[range]);
 const perfMap=useMemo(()=>new Map(perf.map(x=>[x.product_id,x])),[perf]);
 const eventMap=useMemo(()=>{const m=new Map<string,{views:number;unique:number;clicks:number}>();events.forEach(e=>{const x=m.get(e.product_id)||{views:0,unique:0,clicks:0};if(e.event_type==='view')x.views++;if(e.event_type==='unique_view')x.unique++;if(e.event_type==='click')x.clicks++;m.set(e.product_id,x)});return m},[events]);
 const filtered=useMemo(()=>products.filter(p=>{const q=`${p.title} ${p.public_id} ${p.product_type}`.toLowerCase();const okQ=q.includes(search.toLowerCase());const okT=type==='all'||p.product_type===type;const okS=status==='all'||p.status===status;const f=perfMap.get(p.product_id);const okP=performance==='all'||(performance==='sales'&&Number(f?.total_sales||0)>0)||(performance==='views'&&Number(eventMap.get(p.product_id)?.views||0)>0)||(performance==='affiliate'&&Number(f?.affiliate_clicks||0)>0);return okQ&&okT&&okS&&okP}),[products,search,type,status,performance,perfMap,eventMap]);
 const stats=useMemo(()=>({views:events.filter(e=>e.event_type==='view').length,clicks:events.filter(e=>e.event_type==='click').length,sales:perf.reduce((s,p)=>s+Number(p.total_sales||0),0),affiliateSales:perf.reduce((s,p)=>s+Number(p.affiliate_sales||0),0)}),[events,perf]);
 const updateProduct=async(patch:Partial<Product>)=>{if(!editing)return;setSaving(true);setNotice('');const user=(await supabase.auth.getUser()).data.user;const {error:e}=await supabase.from('seller_products').update(patch).eq('product_id',editing.product_id).eq('seller_user_id',user?.id);if(e)setNotice(e.message);else{setEditing(null);await load()}setSaving(false)};
 const setProductStatus=async(p:Product,next:string)=>{const {error:e}=await supabase.from('seller_products').update({status:next}).eq('product_id',p.product_id);if(e)setNotice(e.message);else await load()};
 const createPromotion=async()=>{if(!promoOpen)return;setNotice('');const base=Number(promoBudget);if(!base||!promoPricing){setNotice('Promotion pricing is unavailable or budget is invalid.');return}const {data,error:e}=await supabase.rpc('create_promotion_campaign',{p_asset_type:'product',p_asset_id:promoOpen.product_id,p_goal:promoGoal,p_audience:{},p_location:{},p_placement:{type:'Marketplace'},p_budget:base,p_daily_budget:base/Number(promoDuration),p_duration_days:Number(promoDuration),p_package_id:null,p_idempotency_key:`seller-product:${promoOpen.product_id}:${promoGoal}:${base}:${promoDuration}`});if(e)setNotice(e.message);else{setPromoOpen(null);setNotice(`Promotion ${data?.public_id||''} created with status ${data?.status||'pending_payment'}.`);await load()}};
 if(loading)return <div className="seller-shell theme-dright-light sp-loading"><div className="sp-loading-card"><RefreshCw className="spin" size={24}/><strong>Loading Product Listings</strong><span>Reading authorized Seller data from Supabase…</span></div></div>;
 return <div className="seller-shell theme-dright-light seller-product-page">
  <header className="sp-top"><button className="sp-back" onClick={back}><ArrowLeft size={17}/> Seller Command Center</button><div className="sp-brand"><img src="/src/dright-logo.svg" alt="DRIGHT"/><div><b>DRIGHT</b><span>SELLER / PRODUCT LISTINGS</span></div></div><button className="sp-refresh" onClick={load}><RefreshCw size={16}/> Refresh</button></header>
  <main className="sp-main">
   <section className="sp-hero"><div><span className="sp-kicker">SELLER / VENDOR</span><h1>Product Listings</h1><p>Manage only the products you are authorized to manage. Performance is sourced from DRIGHT's existing product events, orders, affiliate attribution and promotion records.</p></div><button className="sp-create" onClick={()=>setNotice('Create Product remains connected to the existing Seller product workflow; no duplicate product system is created here.')}><Plus size={17}/> Create Product</button></section>
   {notice&&<div className="sp-notice"><ShieldCheck size={17}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
   {error&&<div className="sp-error">{error}</div>}
   <section className="sp-metrics"><Metric icon={Package} label="Products" value={num(products.length)}/><Metric icon={Eye} label="Views" value={num(stats.views)}/><Metric icon={TrendingUp} label="Clicks" value={num(stats.clicks)}/><Metric icon={ShoppingBag} label="Recorded Sales" value={money(stats.sales)}/><Metric icon={Link2} label="Affiliate Sales" value={money(stats.affiliateSales)}/></section>
   <section className="sp-toolbar"><div className="sp-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search Product ID or product name"/></div><div className="sp-filters"><Filter size={15}/><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{[...new Set(products.map(p=>p.product_type))].map(x=><option key={x} value={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['draft','published','paused','rejected','archived'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select><select value={performance} onChange={e=>setPerformance(e.target.value)}><option value="all">All performance</option><option value="sales">Has sales</option><option value="views">Has views</option><option value="affiliate">Has affiliate activity</option></select><select value={range} onChange={e=>setRange(e.target.value)}>{ranges.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></section>
   <section className="sp-table-card"><div className="sp-table-head"><div><span className="sp-kicker">AUTHORIZED INVENTORY</span><h2>My products</h2></div><span>{filtered.length} shown</span></div>{filtered.length===0?<Empty icon={Package} title="No products found" text={products.length?'Adjust your search or filters.':'No products yet. Create Product.'}/>:<div className="sp-table-wrap"><table><thead><tr><th>Product</th><th>Type</th><th>Price</th><th>Views</th><th>Clicks</th><th>Sales</th><th>Revenue</th><th>Affiliate</th><th>Promotion</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=>{const f=perfMap.get(p.product_id);const ev=eventMap.get(p.product_id)||{views:0,unique:0,clicks:0};const promo=promos.find(x=>x.product_id===p.product_id);return <tr key={p.product_id}><td><div className="sp-product"><div className="sp-thumb"><Package size={19}/></div><div><b>{p.title}</b><small>{p.public_id}</small></div></div></td><td><span className="sp-chip">{p.product_type}</span></td><td>{money(Number(p.price),p.currency)}</td><td>{num(ev.views)}</td><td>{num(ev.clicks)}</td><td>{money(Number(f?.total_sales||0),p.currency)}</td><td>{money(Number(f?.revenue_generated||0),p.currency)}</td><td><div className="sp-aff"><b>{num(Number(f?.active_affiliates||0))}</b><small>{num(Number(f?.affiliate_clicks||0))} clicks · {pct(Number(f?.affiliate_conversion_rate||0))}</small></div></td><td>{promo?<span className={`sp-status ${promo.status}`}>{promo.status}</span>:<span className="sp-muted">None</span>}</td><td><span className={`sp-status ${p.status}`}>{p.status}</span></td><td><div className="sp-actions"><button title="View" onClick={()=>setSelected(p)}><Eye size={15}/></button><button title="Edit" onClick={()=>setEditing(p)}><Edit3 size={15}/></button><button title="Analytics" onClick={()=>setSelected(p)}><BarChart3 size={15}/></button><button title="Promote" disabled={!['published'].includes(p.status)} onClick={()=>setPromoOpen(p)}><TrendingUp size={15}/></button>{p.status==='published'?<button title="Pause" onClick={()=>setProductStatus(p,'paused')}><PauseCircle size={15}/></button>:p.status==='paused'?<button title="Resume" onClick={()=>setProductStatus(p,'published')}><CheckCircle2 size={15}/></button>:null}<button title="Archive" onClick={()=>setProductStatus(p,'archived')}><Archive size={15}/></button></div></td></tr>})}</tbody></table></div>}</section>
   <section className="sp-detail-grid"><article className="sp-detail"><span className="sp-kicker">AFFILIATE INTELLIGENCE</span><h2>Seller attribution</h2><p>Affiliate metrics are calculated from DRIGHT's existing attribution and commission records. Sellers cannot edit these values.</p>{selected?<div className="sp-detail-list"><Row label="Product" value={selected.title}/><Row label="Product ID" value={selected.public_id}/><Row label="Affiliate enabled" value={selected.affiliate_enabled?'Yes':'No'}/><Row label="Commission rate" value={pct(Number(selected.affiliate_commission_rate||0))}/><Row label="Affiliate clicks" value={num(Number(perfMap.get(selected.product_id)?.affiliate_clicks||0))}/><Row label="Affiliate sales" value={money(Number(perfMap.get(selected.product_id)?.affiliate_sales||0),selected.currency)}/><Row label="Commission generated" value={money(Number(perfMap.get(selected.product_id)?.affiliate_commission||0),selected.currency)}/></div>:<Empty icon={Link2} title="Select a product" text="Choose View or Analytics to inspect authoritative product-level affiliate performance."/>}</article><article className="sp-detail"><span className="sp-kicker">PROMOTIONS</span><h2>Central promotion engine</h2><p>Promotion creation uses DRIGHT's existing centralized campaign RPC, pricing and packages. No seller-specific promotion engine is created.</p>{promos.length?<div className="sp-promo-list">{promos.map(x=><div key={x.promotion_id}><b>{x.public_id}</b><span>{x.status}</span><small>{num(x.impressions||0)} impressions · {num(x.clicks||0)} clicks · {num(x.conversions||0)} conversions</small></div>)}</div>:<Empty icon={TrendingUp} title="No promotions" text="Promoted products will appear here once a centralized promotion campaign exists."/>}</article></section>
  </main>
  {editing&&<Modal title="Edit product" close={()=>setEditing(null)}><label>Product name<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Description<textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Price<input type="number" min="0" step="0.01" value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><div className="sp-modal-actions"><button onClick={()=>setEditing(null)}>Cancel</button><button className="sp-create" disabled={saving} onClick={()=>updateProduct({title:editing.title,description:editing.description,price:editing.price})}>{saving?'Saving…':'Save changes'}</button></div></Modal>}
  {promoOpen&&<Modal title={`Promote · ${promoOpen.title}`} close={()=>setPromoOpen(null)}><p className="sp-modal-copy">Uses the existing DRIGHT promotion engine. Campaign creation remains pending payment until an authorized payment flow confirms it.</p><label>Goal<select value={promoGoal} onChange={e=>setPromoGoal(e.target.value)}><option value="views">More views</option><option value="visits">More product visits</option><option value="sales">More sales</option><option value="clicks">More clicks</option><option value="conversions">More conversions</option></select></label><label>Budget<input type="number" min="0" step="0.01" value={promoBudget} onChange={e=>setPromoBudget(e.target.value)} placeholder={promoPricing?.min_daily_budget?String(promoPricing.min_daily_budget*Number(promoDuration)):'0.00'}/></label><label>Duration<select value={promoDuration} onChange={e=>setPromoDuration(e.target.value)}>{[1,3,7,14,30].map(x=><option key={x} value={x}>{x} day{x>1?'s':''}</option>)}</select></label>{promoPackages.length>0&&<div className="sp-package-grid">{promoPackages.map(x=><button key={x.package_id} onClick={()=>{setPromoBudget(String(x.price));setPromoDuration(String(x.duration_days))}}><b>{x.name}</b><span>{money(x.price,x.currency)} · {x.duration_days}d</span></button>)}</div>}<div className="sp-modal-actions"><button onClick={()=>setPromoOpen(null)}>Cancel</button><button className="sp-create" onClick={createPromotion}>Create campaign</button></div></Modal>}
 </div>;
}
function Metric({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <article className="sp-metric"><div><Icon size={17}/><span>{label}</span></div><strong>{value}</strong><small>Authoritative DRIGHT data</small></article>}
function Row({label,value}:{label:string;value:string}){return <div className="sp-row"><span>{label}</span><b>{value}</b></div>}
function Empty({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="sp-empty"><Icon size={24}/><strong>{title}</strong><span>{text}</span></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="sp-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="sp-modal"><div className="sp-modal-head"><div><span className="sp-kicker">DRIGHT</span><h3>{title}</h3></div><button onClick={close}><X size={17}/></button></div>{children}</div></div>}
