import React, {FormEvent, useMemo, useState} from 'react';
import {ArrowLeft, Check, ChevronDown, Eye, EyeOff, Globe2, LockKeyhole, Mail, MapPin, ShieldCheck, UserRound} from 'lucide-react';
import {supabase} from './supabase';
import {GoogleAuthButton} from './AuthPages';
import './auth.css';

const COUNTRY_DATA = [
['DZ','Algeria','+213'],['AO','Angola','+244'],['BJ','Benin','+229'],['BW','Botswana','+267'],['BF','Burkina Faso','+226'],['BI','Burundi','+257'],['CV','Cabo Verde','+238'],['CM','Cameroon','+237'],['CF','Central African Republic','+236'],['TD','Chad','+235'],['KM','Comoros','+269'],['CD','Democratic Republic of the Congo','+243'],['CG','Republic of the Congo','+242'],['CI','Côte d’Ivoire','+225'],['DJ','Djibouti','+253'],['EG','Egypt','+20'],['GQ','Equatorial Guinea','+240'],['ER','Eritrea','+291'],['SZ','Eswatini','+268'],['ET','Ethiopia','+251'],['GA','Gabon','+241'],['GM','Gambia','+220'],['GH','Ghana','+233'],['GN','Guinea','+224'],['GW','Guinea-Bissau','+245'],['KE','Kenya','+254'],['LS','Lesotho','+266'],['LR','Liberia','+231'],['LY','Libya','+218'],['MG','Madagascar','+261'],['MW','Malawi','+265'],['ML','Mali','+223'],['MR','Mauritania','+222'],['MU','Mauritius','+230'],['MA','Morocco','+212'],['MZ','Mozambique','+258'],['NA','Namibia','+264'],['NE','Niger','+227'],['NG','Nigeria','+234'],['RW','Rwanda','+250'],['ST','São Tomé and Príncipe','+239'],['SN','Senegal','+221'],['SC','Seychelles','+248'],['SL','Sierra Leone','+232'],['SO','Somalia','+252'],['ZA','South Africa','+27'],['SS','South Sudan','+211'],['SD','Sudan','+249'],['TZ','Tanzania','+255'],['TG','Togo','+228'],['TN','Tunisia','+216'],['UG','Uganda','+256'],['ZM','Zambia','+260'],['ZW','Zimbabwe','+263'],
['AF','Afghanistan','+93'],['AM','Armenia','+374'],['AZ','Azerbaijan','+994'],['BH','Bahrain','+973'],['BD','Bangladesh','+880'],['BT','Bhutan','+975'],['BN','Brunei','+673'],['KH','Cambodia','+855'],['CN','China','+86'],['CY','Cyprus','+357'],['GE','Georgia','+995'],['IN','India','+91'],['ID','Indonesia','+62'],['IR','Iran','+98'],['IQ','Iraq','+964'],['IL','Israel','+972'],['JP','Japan','+81'],['JO','Jordan','+962'],['KZ','Kazakhstan','+7'],['KW','Kuwait','+965'],['KG','Kyrgyzstan','+996'],['LA','Laos','+856'],['LB','Lebanon','+961'],['MY','Malaysia','+60'],['MV','Maldives','+960'],['MN','Mongolia','+976'],['MM','Myanmar','+95'],['NP','Nepal','+977'],['KP','North Korea','+850'],['OM','Oman','+968'],['PK','Pakistan','+92'],['PS','Palestine','+970'],['PH','Philippines','+63'],['QA','Qatar','+974'],['SA','Saudi Arabia','+966'],['SG','Singapore','+65'],['KR','South Korea','+82'],['LK','Sri Lanka','+94'],['SY','Syria','+963'],['TW','Taiwan','+886'],['TJ','Tajikistan','+992'],['TH','Thailand','+66'],['TL','Timor-Leste','+670'],['TR','Türkiye','+90'],['TM','Turkmenistan','+993'],['AE','United Arab Emirates','+971'],['UZ','Uzbekistan','+998'],['VN','Vietnam','+84'],['YE','Yemen','+967'],
['AL','Albania','+355'],['AD','Andorra','+376'],['AT','Austria','+43'],['BY','Belarus','+375'],['BE','Belgium','+32'],['BA','Bosnia and Herzegovina','+387'],['BG','Bulgaria','+359'],['HR','Croatia','+385'],['CZ','Czechia','+420'],['DK','Denmark','+45'],['EE','Estonia','+372'],['FI','Finland','+358'],['FR','France','+33'],['DE','Germany','+49'],['GR','Greece','+30'],['HU','Hungary','+36'],['IS','Iceland','+354'],['IE','Ireland','+353'],['IT','Italy','+39'],['XK','Kosovo','+383'],['LV','Latvia','+371'],['LI','Liechtenstein','+423'],['LT','Lithuania','+370'],['LU','Luxembourg','+352'],['MT','Malta','+356'],['MD','Moldova','+373'],['MC','Monaco','+377'],['ME','Montenegro','+382'],['NL','Netherlands','+31'],['MK','North Macedonia','+389'],['NO','Norway','+47'],['PL','Poland','+48'],['PT','Portugal','+351'],['RO','Romania','+40'],['RU','Russia','+7'],['SM','San Marino','+378'],['RS','Serbia','+381'],['SK','Slovakia','+421'],['SI','Slovenia','+386'],['ES','Spain','+34'],['SE','Sweden','+46'],['CH','Switzerland','+41'],['UA','Ukraine','+380'],['GB','United Kingdom','+44'],['VA','Vatican City','+39'],
['AG','Antigua and Barbuda','+1 268'],['BS','Bahamas','+1 242'],['BB','Barbados','+1 246'],['BZ','Belize','+501'],['CA','Canada','+1'],['CR','Costa Rica','+506'],['CU','Cuba','+53'],['DM','Dominica','+1 767'],['DO','Dominican Republic','+1 809 / +1 829 / +1 849'],['SV','El Salvador','+503'],['GD','Grenada','+1 473'],['GT','Guatemala','+502'],['HT','Haiti','+509'],['HN','Honduras','+504'],['JM','Jamaica','+1 658 / +1 876'],['MX','Mexico','+52'],['NI','Nicaragua','+505'],['PA','Panama','+507'],['KN','Saint Kitts and Nevis','+1 869'],['LC','Saint Lucia','+1 758'],['VC','Saint Vincent and the Grenadines','+1 784'],['TT','Trinidad and Tobago','+1 868'],['US','United States','+1'],
['AR','Argentina','+54'],['BO','Bolivia','+591'],['BR','Brazil','+55'],['CL','Chile','+56'],['CO','Colombia','+57'],['EC','Ecuador','+593'],['GY','Guyana','+592'],['PY','Paraguay','+595'],['PE','Peru','+51'],['SR','Suriname','+597'],['UY','Uruguay','+598'],['VE','Venezuela','+58'],
['AU','Australia','+61'],['FJ','Fiji','+679'],['KI','Kiribati','+686'],['MH','Marshall Islands','+692'],['FM','Micronesia','+691'],['NR','Nauru','+674'],['NZ','New Zealand','+64'],['PW','Palau','+680'],['PG','Papua New Guinea','+675'],['WS','Samoa','+685'],['SB','Solomon Islands','+677'],['TO','Tonga','+676'],['TV','Tuvalu','+688'],['VU','Vanuatu','+678'],
['AS','American Samoa','+1 684'],['AI','Anguilla','+1 264'],['AW','Aruba','+297'],['BM','Bermuda','+1 441'],['VG','British Virgin Islands','+1 284'],['KY','Cayman Islands','+1 345'],['CW','Curaçao','+599'],['FO','Faroe Islands','+298'],['GF','French Guiana','+594'],['PF','French Polynesia','+689'],['GI','Gibraltar','+350'],['GL','Greenland','+299'],['GU','Guam','+1 671'],['HK','Hong Kong','+852'],['IM','Isle of Man','+44 1624'],['MO','Macau','+853'],['MS','Montserrat','+1 664'],['NC','New Caledonia','+687'],['PR','Puerto Rico','+1 787 / +1 939'],['RE','Réunion','+262'],['SX','Sint Maarten','+1 721'],['TC','Turks and Caicos Islands','+1 649'],['VI','U.S. Virgin Islands','+1 340']
] as const;
const countries=COUNTRY_DATA.map(([code,name,dial])=>({code,name,dial}));
type Props={themeClass:string;onBack:()=>void;onComplete:()=>void};
export default function SignupPage({themeClass,onBack,onComplete}:Props){
 const [form,setForm]=useState({firstName:'',lastName:'',email:'',password:'',confirm:'',dob:'',country:'NG',phone:'',address1:'',address2:'',city:'',region:'',postal:''});
 const [showPassword,setShowPassword]=useState(false); const [showConfirm,setShowConfirm]=useState(false); const [terms,setTerms]=useState(false); const [cookies,setCookies]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const selected=countries.find(c=>c.code===form.country)||countries.find(c=>c.code==='NG')!;
 const valid=useMemo(()=>Boolean(form.firstName&&form.lastName&&form.email&&form.password.length>=8&&form.password===form.confirm&&form.dob&&form.country&&form.phone&&form.address1&&form.city&&form.region&&form.postal&&terms&&cookies),[form,terms,cookies]);
 const set=(key:keyof typeof form,value:string)=>setForm(v=>({...v,[key]:value}));
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(!valid){setError('Please complete all required fields, use a valid 8+ character password, and accept the required agreements.');return}const birth=new Date(form.dob);const now=new Date();let age=now.getFullYear()-birth.getFullYear();const m=now.getMonth()-birth.getMonth();if(m<0||(m===0&&now.getDate()<birth.getDate()))age--;if(age<13){setError('You must be at least 13 years old to create a DRIGHT account.');return}setLoading(true);const {data,error:authError}=await supabase.auth.signUp({email:form.email,password:form.password,options:{emailRedirectTo:window.location.origin,data:{first_name:form.firstName,last_name:form.lastName,date_of_birth:form.dob,country_code:form.country,phone:form.phone,address_line1:form.address1,address_line2:form.address2,city:form.city,region:form.region,postal_code:form.postal}}});if(authError){setLoading(false);setError(authError.message);return}if(data.user){const normalizedPhone=`${selected.dial.replace(/\s/g,'').split('/')[0]}${form.phone.replace(/\s|-/g,'')}`;await supabase.from('profiles').upsert({id:data.user.id,first_name:form.firstName,last_name:form.lastName,email:form.email,date_of_birth:form.dob,country_code:form.country,phone:normalizedPhone,address_line1:form.address1,address_line2:form.address2,city:form.city,region:form.region,postal_code:form.postal,terms_accepted_at:new Date().toISOString(),cookies_accepted_at:new Date().toISOString(),updated_at:new Date().toISOString()});}setLoading(false);onComplete()};
 return <div className={`signup-page ${themeClass}`}>
  <div className="signup-top"><button className="signup-back" onClick={onBack}><ArrowLeft size={17}/> Back</button><div className="signup-mini-brand"><span className="signup-mini-d">D</span><strong>DRIGHT</strong></div><span className="signup-signin">Already have an account? <button onClick={onBack}>Sign in</button></span></div>
  <main className="signup-shell"><section className="signup-intro"><div className="signup-logo-mark"><span>D</span></div><span className="signup-kicker">JOIN DRIGHT</span><h1>Create your DRIGHT account.</h1><p>Discover, buy, sell, promote, learn and find opportunities across the DRIGHT ecosystem.</p><div className="signup-note"><ShieldCheck size={18}/><span>DRIGHT accounts start at age 13. Some features may have higher age requirements depending on your country.</span></div></section>
   <form className="signup-card" onSubmit={submit}><div className="signup-card-head"><div><h2>Create account</h2><p>Your account details</p></div><span className="signup-step">1 of 1</span></div>
    <GoogleAuthButton label="Continue with Google" onError={setError}/><div className="signup-divider"><span>or create with email</span></div>
    <div className="signup-grid two"><Field label="First name" required value={form.firstName} onChange={v=>set('firstName',v)} icon={<UserRound size={16}/>}/><Field label="Last name" required value={form.lastName} onChange={v=>set('lastName',v)} icon={<UserRound size={16}/>}/></div>
    <Field label="Email address" type="email" required value={form.email} onChange={v=>set('email',v)} icon={<Mail size={16}/>}/>
    <div className="signup-grid two"><Field label="Password" required type={showPassword?'text':'password'} value={form.password} onChange={v=>set('password',v)} icon={<LockKeyhole size={16}/>} trailing={<button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button>}/><Field label="Confirm password" required type={showConfirm?'text':'password'} value={form.confirm} onChange={v=>set('confirm',v)} icon={<LockKeyhole size={16}/>} trailing={<button type="button" onClick={()=>setShowConfirm(v=>!v)}>{showConfirm?<EyeOff size={17}/>:<Eye size={17}/>}</button>}/></div>
    <div className="signup-grid two"><Field label="Date of birth" required type="date" value={form.dob} onChange={v=>set('dob',v)}/><label className="signup-field"><span>Country <b>*</b></span><div className="signup-input"><Globe2 size={16}/><select value={form.country} onChange={e=>set('country',e.target.value)}>{countries.map(c=><option key={c.code} value={c.code}>{c.name} ({c.dial})</option>)}</select><ChevronDown size={15}/></div></label></div>
    <label className="signup-field"><span>Phone number <b>*</b></span><div className="signup-phone"><div className="signup-code">{selected.dial}</div><input inputMode="tel" value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="International phone number"/></div></label>
    <div className="signup-section-title"><MapPin size={16}/><strong>Address</strong><small>Google address search can be connected later.</small></div>
    <Field label="Address line 1" required value={form.address1} onChange={v=>set('address1',v)} icon={<MapPin size={16}/>}/><Field label="Address line 2" value={form.address2} onChange={v=>set('address2',v)}/>
    <div className="signup-grid three"><Field label="City" required value={form.city} onChange={v=>set('city',v)}/><Field label="State / Province / Region" required value={form.region} onChange={v=>set('region',v)}/><Field label="Postal / ZIP code" required value={form.postal} onChange={v=>set('postal',v)}/></div>
    <div className="signup-consents"><Consent checked={terms} setChecked={setTerms}>I agree to DRIGHT's <button type="button">Terms and Conditions</button>.</Consent><Consent checked={cookies} setChecked={setCookies}>I accept DRIGHT's <button type="button">Cookie Policy</button> and understand that essential cookies are required for the service.</Consent></div>
    {error&&<div className="signup-error">{error}</div>}<button className="signup-submit" disabled={!valid||loading} type="submit">{loading?'Creating account…':'Create my DRIGHT account'} <Check size={17}/></button><p className="signup-legal">By creating an account, you confirm that the information provided is accurate. Age and feature eligibility are applied according to DRIGHT rules and applicable country requirements.</p>
   </form></main></div>
}
function Field({label,required,type='text',value,onChange,icon,trailing}:{label:string;required?:boolean;type?:string;value:string;onChange:(v:string)=>void;icon?:React.ReactNode;trailing?:React.ReactNode}){return <label className="signup-field"><span>{label} {required&&<b>*</b>}</span><div className="signup-input">{icon}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={type==='date'?'':'Enter '+label.toLowerCase()}/>{trailing}</div></label>}
function Consent({checked,setChecked,children}:{checked:boolean;setChecked:(v:boolean)=>void;children:React.ReactNode}){return <label className="signup-consent"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span className="signup-check">{checked&&<Check size={13}/>}</span><span>{children}</span></label>}