import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,ChevronDown,Info,MapPin,Megaphone,Package,RefreshCw,Search,ShieldCheck,Target,WalletCards} from 'lucide-react';
import {supabase} from './supabase';
import './universal-promote.css';

type Step='goal'|'asset'|'audience'|'location'|'placement'|'budget'|'review';
type Asset={asset_type:string;asset_id:string;public_id:string;title:string;status:string;currency:string;price:number};
type Package={package_id:string;public_id:string;name:string;description:string;price:number;currency:string;duration_days:number;estimated_impressions_min:number|null;estimated_impressions_max:number|null;estimated_reach_min:number|null;estimated_reach_max:number|null;estimated_views_min:number|null;estimated_views_max:number|null;estimated_clicks_min:number|null;estimated_clicks_max:number|null;placement:any;targeting_rules:any;eligibility:any;status:string;sort_order:number};
type Pricing={pricing_id:string;public_id:string;name:string;currency:string;pricing_model:string;cpm:number;cpc:number;cost_per_reach:number;min_daily_budget:number;max_campaign_budget:number;platform_fee_rate:number;tax_rate:number;default_ctr:number;default_conversion_rate:number;config:any;status:string};
const goals=[['views','Get more views','Increase qualified exposure'],['visits','Get more product visits','Send people to the asset'],['sales','Get more sales','Optimize toward purchases'],['clicks','Get more clicks','Drive traffic to the destination'],['conversions','Get more conversions','Drive measurable outcomes']];
const money=(n:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(n)||0);
const range=(a:number|null,b:number|null)=>a==null&&b==null?'Not configured':a===b?String(a):`${a??'—'}–${b??'—'}`;

export default function UniversalPromote({onBack}:{onBack:()=>void}){
 const [step,setStep]=useState<Step>('goal');
 const [assets,setAssets]=useState<Asset[]>([]); const [packages,setPackages]=useState<Package[]>([]); const [pricing,setPricing]=useState<Pricing|null>(null);
 const [asset,setAsset]=useState<Asset|null>(null); const [goal,setGoal]=useState('views'); const [audience,setAudience]=useState(''); const [location,setLocation]=useState(''); const [placement,setPlacement]=useState(''); const [budget,setBudget]=useState(''); const [duration,setDuration]=useState('1'); const [selectedPackage,setSelectedPackage]=useState<Package|null>(null);
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [created,setCreated]=useState<any>(null); const [mine,setMine]=useState<any[]>([]); const [tab,setTab]=useState<'create'|'dashboard'|'mine'>('create'); const [search,setSearch]=useState('');
 useEffect(()=>{(async()=>{setLoading(true);const [a,p,r,m]=await Promise.all([supabase.rpc('get_my_promotion_assets'),supabase.from('promotion_packages').select('*').eq('status','active').order('sort_order'),supabase.from('promotion_pricing').select('*').eq('status','active').order('effective_at',{ascending:false}).limit(1).maybeSingle(),supabase.rpc('get_my_promotion_dashboard')]);if(a.error)setError(a.error.message);setAssets(a.data||[]);setPackages(p.error?[]:(p.data||[]));setPricing(r.data||null);setMine(m.error?[]:(m.data?.campaigns||[]));setLoading(false)})()},[]);
 const filteredAssets=useMemo(()=>assets.filter(x=>`${x.public_id} ${x.title}`.toLowerCase().includes(search.toLowerCase())),[assets,search]);
 const base=selectedPackage?Number(selectedPackage.price):Number(budget)||0; const fee=pricing?base*Number(pricing.platform_fee_rate||0):0; const tax=pricing?(base+fee)*Number(pricing.tax_rate||0):0; const total=base+fee+tax;
 const next=()=>{setError('');if(step==='goal')setStep('asset');else if(step==='asset')setStep('audience');else if(step==='audience')setStep('location');else if(step==='location')setStep('placement');else if(step==='placement')setStep('budget');else if(step==='budget')setStep('review')};
 const back=()=>{if(step==='goal')onBack();else if(step==='asset')setStep('goal');else if(step==='audience')setStep('asset');else if(step==='location')setStep('audience');else if(step==='placement')setStep('location');else if(step==='budget')setStep('placement');else setStep('budget')};
 const create=async()=>{if(!asset){setError('Select an eligible asset.');return}if(!base){setError('Configure a budget or package.');return}setSaving(true);setError('');const {data,error:e}=await supabase.rpc('create_promotion_campaign',{p_asset_type:asset.asset_type,p_asset_id:asset.asset_id,p_goal:goal,p_audience:{description:audience},p_location:{description:location},p_placement:{type:placement},p_budget:base,p_daily_budget:base/Math.max(1,Number(duration)),p_duration_days:Number(duration),p_package_id:selectedPackage?.package_id||null,p_idempotency_key:`promote:${asset.asset_id}:${goal}:${base}:${duration}:${selectedPackage?.package_id||'custom'}`});if(e)setError(e.message);else {setCreated(data);setMine(v=>[data,...v]);setTab('mine')}setSaving(false)};
 const tabs=[['create','Create'],['dashboard','Dashboard'],['mine','Mine']] as const;
 if(loading)return <main className="promote-page"><div className="promote-loading"><RefreshCw className="promote-spin"/> Loading your promotion workspace…</div></main>;
 return <main className="promote-page"><header className="promote-header"><button className="promote-back" onClick={onBack}><ArrowLeft size={18}/></button><div><span>DRIGHT</span><h1>Promote</h1></div><button className="promote-help" title="Promotion help"><Info size={18}/></button></header>
  <div className="promote-tabs">{tabs.map(([k,label])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{label}</button>)}</div>
  {error&&<div className="promote-error"><ShieldCheck size={17}/><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}
  {tab==='create'&&<><div className="promote-progress"><span>Campaign setup</span><strong>{step==='goal'?1:step==='asset'?2:step==='audience'?3:step==='location'?4:step==='placement'?5:step==='budget'?6:7} / 7</strong></div>
   <section className="promote-layout"><div className="promote-main-card">
    {step==='goal'&&<><Kicker text="01 · Goal"/><h2>Choose your goal</h2><p>Pick the outcome that matches the asset you want to promote.</p><div className="promote-choice-grid">{goals.map(([id,title,desc])=><button key={id} className={goal===id?'selected':''} onClick={()=>setGoal(id)}><span><Target size={19}/></span><b>{title}</b><small>{desc}</small>{goal===id&&<CheckCircle2 size={17}/>}</button>)}</div></>}
    {step==='asset'&&<><Kicker text="02 · Asset"/><h2>Select what to promote</h2><p>Only assets owned by your authorized DRIGHT profile are shown.</p><div className="promote-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by DRIGHT public ID or title"/></div><div className="promote-asset-list">{filteredAssets.length?filteredAssets.map(a=><button key={a.asset_id} className={asset?.asset_id===a.asset_id?'selected':''} onClick={()=>setAsset(a)}><span className="promote-asset-icon"><Package size={19}/></span><span><b>{a.title}</b><small>{a.public_id} · {a.asset_type} · {a.status}</small></span>{asset?.asset_id===a.asset_id&&<CheckCircle2 size={18}/>}</button>):<Empty text="No eligible assets are available yet."/>}</div></>}
    {step==='audience'&&<><Kicker text="03 · Audience"/><h2>Define your audience</h2><p>Describe the audience you want DRIGHT delivery to prioritize.</p><textarea value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Example: people interested in AI, digital business and productivity"/><div className="promote-callout"><Info size={17}/><span>Audience targeting is a delivery preference. It does not guarantee reach, views or conversions.</span></div></>}
    {step==='location'&&<><Kicker text="04 · Location"/><h2>Choose location</h2><p>Enter a country, region, city or broader location target.</p><div className="promote-field"><MapPin size={18}/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Worldwide, United States, Lagos…"/></div></>}
    {step==='placement'&&<><Kicker text="05 · Placement"/><h2>Choose placement</h2><p>Select where your paid promotion is eligible to appear.</p><div className="promote-choice-grid compact">{['Marketplace','Discovery','Sponsored listings'].map(x=><button key={x} className={placement===x?'selected':''} onClick={()=>setPlacement(x)}><span><Megaphone size={19}/></span><b>{x}</b><small>Sponsored placement</small>{placement===x&&<CheckCircle2 size={17}/>}</button>)}</div></>}
    {step==='budget'&&<><Kicker text="06 · Budget"/><h2>Set budget and duration</h2><p>Pricing and limits are validated by the server before a campaign is created.</p>{packages.length>0&&<div className="promote-packages">{packages.map(p=><button key={p.package_id} className={selectedPackage?.package_id===p.package_id?'selected':''} onClick={()=>{setSelectedPackage(p);setBudget(String(p.price));setDuration(String(p.duration_days))}}><div><b>{p.name}</b><small>{p.description||'Configured DRIGHT promotion package'}</small></div><strong>{money(p.price,p.currency)}</strong><span>Est. reach {range(p.estimated_reach_min,p.estimated_reach_max)} · views {range(p.estimated_views_min,p.estimated_views_max)} · clicks {range(p.estimated_clicks_min,p.estimated_clicks_max)}</span></button>)}</div>}<div className="promote-budget-row"><label>Custom budget<input type="number" min="0" step="0.01" value={budget} onChange={e=>{setBudget(e.target.value);setSelectedPackage(null)}} placeholder="0.00"/></label><label>Duration<select value={duration} onChange={e=>setDuration(e.target.value)}>{[1,3,7,14,30].map(x=><option key={x} value={x}>{x} day{x>1?'s':''}</option>)}</select></label></div>{pricing&&<p className="promote-note">Current server pricing: minimum daily budget {money(pricing.min_daily_budget,pricing.currency)}. Maximum campaign budget {pricing.max_campaign_budget>0?money(pricing.max_campaign_budget,pricing.currency):'Not configured'}.</p>}</>}
    {step==='review'&&<><Kicker text="07 · Review"/><h2>Review promotion</h2><p>Review the configuration before creating the campaign.</p><div className="promote-review"><Row label="Goal" value={goals.find(x=>x[0]===goal)?.[1]||goal}/><Row label="Asset" value={asset?`${asset.title} · ${asset.public_id}`:'Not selected'}/><Row label="Audience" value={audience||'Not specified'}/><Row label="Location" value={location||'Not specified'}/><Row label="Placement" value={placement||'Not selected'}/><Row label="Duration" value={`${duration} day${Number(duration)>1?'s':''}`}/><Row label="Promotion cost" value={money(base,pricing?.currency||asset?.currency||'USD')}/><Row label="Platform fees" value={pricing?money(fee,pricing.currency):'Not configured'}/><Row label="Taxes" value={pricing?money(tax,pricing.currency):'Not configured'}/><Row label="Total" value={pricing?money(total,pricing.currency):'Not configured'}/></div><div className="promote-callout"><ShieldCheck size={17}/><span>Creating this campaign does not mark it paid or active. Payment confirmation and activation remain server-authoritative.</span></div></>}
    <div className="promote-actions"><button className="secondary" onClick={back}><ArrowLeft size={16}/> Back</button>{step!=='review'?<button className="primary" onClick={next}>Continue <ArrowRight size={16}/></button>:<button className="primary" onClick={create} disabled={saving||!pricing}>{saving?'Creating…':'Create campaign'}</button>}</div>
   </div><aside className="promote-summary"><div className="summary-head"><span>Promotion summary</span><WalletCards size={18}/></div><div className="summary-asset">{asset?<><div className="summary-thumb"><Package size={22}/></div><div><b>{asset.title}</b><small>{asset.public_id}</small></div></>:<div className="summary-empty">Select an asset to preview it here.</div>}</div><div className="summary-line"><span>Goal</span><b>{goals.find(x=>x[0]===goal)?.[1]}</b></div><div className="summary-line"><span>Duration</span><b>{duration} day{Number(duration)>1?'s':''}</b></div><div className="summary-line"><span>Cost</span><b>{money(base,pricing?.currency||'USD')}</b></div><div className="summary-total"><span>Total</span><strong>{pricing?money(total,pricing.currency):'Pricing unavailable'}</strong></div><small className="summary-disclosure">Estimates are not guaranteed. Paid placements are labeled Sponsored.</small></aside></section></>}
  {tab==='dashboard'&&<Dashboard campaigns={mine}/>} {tab==='mine'&&<Mine campaigns={mine} created={created}/>} 
 </main>;
}
function Dashboard({campaigns}:{campaigns:any[]}){const active=campaigns.filter(x=>['active','scheduled','approved'].includes(x.status)).length;const spend=campaigns.reduce((s,x)=>s+Number(x.spend||0),0);return <section className="promote-dashboard"><Kicker text="Promotion intelligence"/><h2>Your promotion dashboard</h2><p>Actual campaign records only. Metrics remain empty until DRIGHT records delivery events.</p><div className="promote-stat-grid"><Stat label="Campaigns" value={String(campaigns.length)}/><Stat label="Active" value={String(active)}/><Stat label="Spend" value={spend?'Recorded':'No data yet'}/><Stat label="Conversions" value={campaigns.reduce((s,x)=>s+Number(x.conversions||0),0)?String(campaigns.reduce((s,x)=>s+Number(x.conversions||0),0)):'No data yet'}/></div><div className="promote-table">{campaigns.length===0?<Empty text="No performance data yet."/>:campaigns.map(x=><div className="promote-campaign-row" key={x.public_id}><span><b>{x.public_id}</b><small>{x.asset_type} · {x.promotion_goal||'promotion'}</small></span><strong>{x.status}</strong><span>{Number(x.impressions||0)>0?`${x.impressions} impressions`:'No delivery data yet'}</span></div>)}</div></section>}
function Mine({campaigns,created}:{campaigns:any[];created:any}){return <section className="promote-dashboard"><Kicker text="Mine"/><h2>Your campaigns</h2><p>Campaigns created for your authorized profile.</p>{created&&<div className="promote-success"><CheckCircle2 size={18}/><span>Campaign <b>{created.public_id}</b> was created with status <b>{created.status}</b>. It is not marked paid or active by the frontend.</span></div>}<div className="promote-table">{campaigns.length===0?<Empty text="No promotions yet. Create your first promotion to start reaching more people."/>:campaigns.map(x=><div className="promote-campaign-row" key={x.public_id}><span><b>{x.public_id}</b><small>{x.asset_type} · {x.promotion_goal||'promotion'}</small></span><strong>{x.status}</strong><span>{x.starts_at?new Date(x.starts_at).toLocaleDateString():'—'}</span></div>)}</div></section>}
function Kicker({text}:{text:string}){return <span className="promote-kicker">{text}</span>}; function Row({label,value}:{label:string;value:string}){return <div className="review-row"><span>{label}</span><b>{value}</b></div>}; function Stat({label,value}:{label:string;value:string}){return <div className="promote-stat"><small>{label}</small><strong>{value}</strong></div>}; function Empty({text}:{text:string}){return <div className="promote-empty">{text}</div>}
